source "$( "${HOME}/.bash/resolve.sh" "aliases.sh" )"
source "$( "${HOME}/.bash/resolve.sh" "bash_options.sh" )"
source "$( "${HOME}/.bash/resolve.sh" "bash_prompt.sh" )"
source "$( "${HOME}/.bash/resolve.sh" "mysql.sh" )"
source "$( "${HOME}/.bash/resolve.sh" "thefuck.sh" )"
