#!/bin/sh

set_border(){
  case "$1" in
    "large")
      bspc config border_width 20
    ;;

    "regular")
      bspc config border_width 2
    ;;
  esac
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  set -euo pipefail
  set_border "$1"
fi
