#!/bin/bash

if [ $(os) != 'OSX' ]; then
    alias ls="/bin/ls --color=always -F"
else
    alias ls="/bin/ls -GF"
fi
alias l="ls -l"
alias la="l -a"
alias ..='cd ..'
alias s='screen -RD'
alias ss='python -m SimpleHTTPServer 3000'

function npmi () {
    npm install --save "$@" && npm shrinkwrap
}

touch $HOME/opt/.profile.d/bash/aliases && source $HOME/opt/.profile.d/bash/aliases
