#!/bin/bash

USERPATH=
[[ -d $HOME/bin                             ]] && USERPATH=$USERPATH:$HOME/bin
[[ -d $HOME/opt/bin                         ]] && USERPATH=$USERPATH:$HOME/opt/bin
[[ -d $HOME/.rvm/bin                        ]] && USERPATH=$USERPATH:$HOME/.rvm/bin
[[ -d $HOME/.rbenv/bin                      ]] && USERPATH=$USERPATH:$HOME/.rbenv/bin
[[ -d $HOME/AppData/Roaming/npm             ]] && USERPATH=$USERPATH:$HOME/AppData/Roaming/npm
[[ -d $HOME/opt/android-sdk/platform-tools  ]] && USERPATH=$USERPATH:$HOME/opt/android-sdk/platform-tools
[[ -d /cygdrive/c/Program\ Files/nodejs     ]] && USERPATH=$USERPATH:/cygdrive/c/Program\ Files/nodejs

export PATH=$USERPATH:$PATH
