#!/bin/bash

[[ -d $HOME/bin                                     ]] && export PATH=$PATH:$HOME/bin
[[ -d $HOME/.rvm/bin                                ]] && export PATH=$PATH:$HOME/.rvm/bin
[[ -d $HOME/AppData/Roaming/npm                     ]] && export PATH=$PATH:$HOME/AppData/Roaming/npm
[[ -d $HOME/Software/android-sdks/platform-tools    ]] && export PATH=$PATH:$HOME/Software/android-sdks/platform-tools
[[ -d /cygdrive/c/Program\ Files/nodejs             ]] && export PATH=$PATH:/cygdrive/c/Program\ Files/nodejs
