#!/bin/bash
mkdir -p ${HOME}/opt/.profile.d/bash

DIR=${HOME}/.profile.d/bash
source ${DIR}/path
source ${DIR}/locale
source ${DIR}/env
source ${DIR}/options
source ${DIR}/man
source ${DIR}/windows
source ${DIR}/rvm
source ${DIR}/rbenv

[[ "$-" != *i* ]] && return # The following should only be started when interactive
source ${DIR}/aliases
source ${DIR}/options
source ${DIR}/prompt
