#!/bin/bash

if [ $(os) = 'Windows' ]; then
    export DISPLAY=:0.0

    if [ -x /usr/local/bin/ssh-pageant ]; then
        eval $(/usr/local/bin/ssh-pageant -qra /tmp/.ssh-pageant)
    else
        echo "Install ssh-pagent"
    fi
fi

touch $HOME/opt/.profile.d/bash/windows && source $HOME/opt/.profile.d/bash/windows
