#!/bin/bash

if [ $(os) = 'Windows' ]; then
    export DISPLAY=:0.0

    export SSH_AUTH_SOCK=/tmp/.ssh-socket
    ssh-add -l >/dev/null 2>&1
    if [ $? = 2 ]; then
        rm -f $SSH_AUTH_SOCK
        eval $(ssh-agent -a $SSH_AUTH_SOCK)
        echo $SSH_AGENT_PID > /tmp/.ssh-agent-pid
    fi
fi
