#! /bin/sh
set -euo pipefail

__DIR__="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

rm -f "$__DIR__/fifo.sxhkd"
mkfifo "$__DIR__/fifo.sxhkd"
sxhkd -c "$__DIR__/sxhkdrc" -s "$__DIR__/fifo.sxhkd" &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0


bspc config border_width 2

"$__DIR__/set-gap.sh" 12

bspc config split_ratio          0.52

bspc rule --add Pithos desktop="^0" state=floating
bspc rule --add "Messenger for Desktop" desktop="^0" state=floating
