#! /bin/sh
set -euo pipefail

__DIR__="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$__DIR__/bspwmrc.d/set_gap_and_padding"
source "$__DIR__/bspwmrc.d/set_border"

msxhkd start "$__DIR__/msxhkd.d" &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0


set_border regular
set_gap_and_padding 12

bspc config split_ratio          0.52

bspc rule --add Pithos desktop="^0" state=floating
bspc rule --add "Messenger for Desktop" desktop="^0" state=floating
