#! /bin/sh
set -euo pipefail

__DIR__="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0


bspc config border_width 2

"$__DIR__/set-gap.sh" 12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule --add Pithos desktop="^0" state=floating
bspc rule --add "Messenger for Desktop" desktop="^0" state=floating
