(let ((directories '("key-chord" "evil")))
  (dolist (directory directories)
    (add-to-list 'load-path (expand-file-name
      (concat "~/.emacs.d/packages/" directory "/")
    ))
  )
)

(let ((init-d (expand-file-name "~/.emacs.d/init.d/")))
  (byte-recompile-directory init-d 0)
  (let ((files (directory-files init-d t "\\.elc$")))
    (dolist (file files)
      (load file)
    )
  )
)
